use anyhow::Result;
use async_trait::async_trait;

use crate::domain::SystemEvent;

#[async_trait]
pub trait EventCoordinator: Send + Sync + 'static {
    async fn next_event(&self) -> Result<SystemEvent>;

    /// Enqueue a new event into the event coordinator's event stream
    ///
    /// This method allows dynamically adding events during runtime,
    /// such as signals generated by signal generators.
    async fn enqueue_event(&self, event: SystemEvent) -> Result<()>;
}
