//! Redemption types for binary market pair redemption.
//!
//! In binary prediction markets (Up/Down), holding 1 Up + 1 Down token can be
//! redeemed for exactly $1. This module provides types for expressing redemption
//! policies and actions.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Declarative constraint on paired inventory for binary markets.
///
/// The position manager enforces this policy by automatically generating
/// redemption actions when the constraint is violated.
///
/// # Example: Dynamic Policy Adjustment
///
/// ```ignore
/// // During active trading: tolerate capital lock-up
/// let policy = RedemptionPolicy::new(market, up, down, 50.0);
///
/// // Approaching close: start tightening
/// let policy = RedemptionPolicy::new(market, up, down, 5.0);
///
/// // After market close: redeem everything
/// let policy = RedemptionPolicy::new(market, up, down, 0.1);
/// ```
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct RedemptionPolicy {
    /// Market/condition identifier (e.g., the binary market ID)
    pub market: String,

    /// Asset ID for the "Up" token
    pub up_asset_id: String,

    /// Asset ID for the "Down" token
    pub down_asset_id: String,

    /// Maximum unredeemed pair value to hold.
    /// When min(up_qty, down_qty) exceeds this, system auto-redeems the excess.
    pub max_unredeemed_pair_value: f64,
}

impl RedemptionPolicy {
    /// Create a new redemption policy.
    pub fn new(
        market: String,
        up_asset_id: String,
        down_asset_id: String,
        max_unredeemed_pair_value: f64,
    ) -> Self {
        Self {
            market,
            up_asset_id,
            down_asset_id,
            max_unredeemed_pair_value,
        }
    }

    /// Calculate how many pairs should be redeemed given current holdings.
    /// Returns 0.0 if no redemption needed.
    pub fn pairs_to_redeem(&self, up_qty: f64, down_qty: f64) -> f64 {
        let paired_qty = up_qty.min(down_qty);
        if paired_qty > self.max_unredeemed_pair_value {
            paired_qty - self.max_unredeemed_pair_value
        } else {
            0.0
        }
    }
}

/// Internal action generated when redemption policy is violated.
/// Not exposed in signals - generated by position manager during reconciliation.
#[derive(Debug, Clone)]
pub struct RedemptionAction {
    /// Market/condition identifier
    pub market: String,

    /// Asset ID for the "Up" token
    pub up_asset_id: String,

    /// Asset ID for the "Down" token
    pub down_asset_id: String,

    /// Quantity of pairs to redeem
    pub quantity: f64,

    /// Timestamp when action was generated
    pub timestamp: DateTime<Utc>,
}

impl RedemptionAction {
    /// Create a new redemption action.
    pub fn new(
        market: String,
        up_asset_id: String,
        down_asset_id: String,
        quantity: f64,
        timestamp: DateTime<Utc>,
    ) -> Self {
        Self {
            market,
            up_asset_id,
            down_asset_id,
            quantity,
            timestamp,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_redemption_policy_new() {
        let policy = RedemptionPolicy::new(
            "MARKET-1".to_string(),
            "UP-ASSET".to_string(),
            "DOWN-ASSET".to_string(),
            50.0,
        );

        assert_eq!(policy.market, "MARKET-1");
        assert_eq!(policy.up_asset_id, "UP-ASSET");
        assert_eq!(policy.down_asset_id, "DOWN-ASSET");
        assert_eq!(policy.max_unredeemed_pair_value, 50.0);
    }

    #[test]
    fn test_pairs_to_redeem_no_redemption_needed() {
        let policy = RedemptionPolicy::new(
            "MARKET-1".to_string(),
            "UP".to_string(),
            "DOWN".to_string(),
            50.0,
        );

        // Both below threshold
        assert_eq!(policy.pairs_to_redeem(30.0, 20.0), 0.0);
        assert_eq!(policy.pairs_to_redeem(50.0, 50.0), 0.0);
        assert_eq!(policy.pairs_to_redeem(100.0, 0.0), 0.0);
    }

    #[test]
    fn test_pairs_to_redeem_redemption_needed() {
        let policy = RedemptionPolicy::new(
            "MARKET-1".to_string(),
            "UP".to_string(),
            "DOWN".to_string(),
            50.0,
        );

        // Paired amount exceeds threshold
        assert_eq!(policy.pairs_to_redeem(100.0, 100.0), 50.0);
        assert_eq!(policy.pairs_to_redeem(75.0, 60.0), 10.0); // min=60, excess=10
        assert_eq!(policy.pairs_to_redeem(200.0, 150.0), 100.0); // min=150, excess=100
    }

    #[test]
    fn test_pairs_to_redeem_asymmetric() {
        let policy = RedemptionPolicy::new(
            "MARKET-1".to_string(),
            "UP".to_string(),
            "DOWN".to_string(),
            10.0,
        );

        // Only the minimum of both sides counts
        assert_eq!(policy.pairs_to_redeem(100.0, 20.0), 10.0); // min=20, excess=10
        assert_eq!(policy.pairs_to_redeem(20.0, 100.0), 10.0); // min=20, excess=10
    }

    #[test]
    fn test_redemption_policy_serialization() {
        let policy = RedemptionPolicy::new(
            "MARKET-1".to_string(),
            "UP-ASSET".to_string(),
            "DOWN-ASSET".to_string(),
            50.0,
        );

        let json = serde_json::to_string(&policy).unwrap();
        let deserialized: RedemptionPolicy = serde_json::from_str(&json).unwrap();

        assert_eq!(policy, deserialized);
    }

    #[test]
    fn test_redemption_action_new() {
        let timestamp = Utc::now();
        let action = RedemptionAction::new(
            "MARKET-1".to_string(),
            "UP".to_string(),
            "DOWN".to_string(),
            25.0,
            timestamp,
        );

        assert_eq!(action.market, "MARKET-1");
        assert_eq!(action.up_asset_id, "UP");
        assert_eq!(action.down_asset_id, "DOWN");
        assert_eq!(action.quantity, 25.0);
        assert_eq!(action.timestamp, timestamp);
    }
}
