use std::{
    collections::HashMap,
    sync::{
        Arc, Mutex as StdMutex,
        atomic::{AtomicU64, Ordering},
    },
};

use anyhow::{Result, anyhow};
use async_trait::async_trait;
use chrono::{DateTime, Duration, Utc};
use rand::Rng;
use tokio::sync::RwLock;
use tracing::{debug, instrument};

use popeyes_trading_types::{PolymarketTradeEvent, TokenTradeEvent, TradeSide};

use crate::config::LatencySimulationConfig;

use super::metrics::PaperTradingMetrics;

/// Configuration for paper trading fill simulation.
///
/// This struct groups fill simulation options that control how the
/// `PaperTradingOrderExecutor` simulates order fills against live market data.
#[derive(Debug, Clone)]
pub struct PaperTradingConfig {
    /// If true, sell orders require positive inventory to fill.
    /// This prevents "naked shorting" which is not realistic for venues like Polymarket.
    /// Default: true
    pub enforce_inventory_constraints: bool,
    /// Latency simulation for realistic fill modeling.
    /// When set, orders are not eligible for fills until after a simulated placement latency.
    /// Default: None (immediate eligibility)
    pub latency_config: Option<LatencySimulationConfig>,
}

impl Default for PaperTradingConfig {
    fn default() -> Self {
        Self {
            enforce_inventory_constraints: true,
            latency_config: None,
        }
    }
}
use crate::execution::{
    OrderExecutor,
    events::{ExecutionEvent, LimitOrderEvent, OrderSide, RedemptionEvent, TimeInForce},
    lifecycle::{
        LifecycleCancelConfirmed, LifecycleCancelRequest, LifecycleCancelRequestOutcome,
        LifecycleEngine, LifecycleFillEvidence, LifecycleOrderRef, LifecyclePlaceRequest,
        LifecyclePlaceSuccess, LifecycleState, TerminalReason,
    },
    order::{Order, OrderType},
};
use crate::position::ExitMode;
use crate::signal::RedemptionAction;

/// Internal representation of a pending limit order in the paper trading executor.
///
/// This struct tracks the state of a limit order that has been placed but not yet
/// filled or cancelled. Similar to `PendingBacktestOrder` but designed for
/// continuous operation with live trade events.
#[derive(Debug, Clone)]
pub struct PendingPaperOrder {
    /// Unique order identifier (generated by executor)
    pub order_id: String,
    /// Asset identifier (token mint or asset_id)
    pub mint: String,
    /// Market/condition ID (for orderbook venues)
    pub market: Option<String>,
    /// Order side (Buy or Sell)
    pub side: OrderSide,
    /// Limit price
    pub price: f64,
    /// Original order size
    pub original_size: f64,
    /// Remaining unfilled size
    pub remaining_size: f64,
    /// When the order was placed
    pub placed_at: DateTime<Utc>,
    /// Time-in-force constraint
    pub time_in_force: TimeInForce,
    /// Signal ID that originated this order
    pub signal_id: Option<String>,
    /// Exit mode for positions created from fills of this order.
    /// Used to propagate StrategyManaged mode from intent-based signals.
    pub exit_mode: Option<ExitMode>,
    /// Arbitrary debug context data from the signal
    pub context: Option<serde_json::Value>,
    /// Earliest timestamp when this order is eligible for fills.
    /// Models order placement latency.
    /// Orders are not matched against trades with timestamp < eligible_for_fills_at.
    pub eligible_for_fills_at: DateTime<Utc>,
    /// When present, cancellation confirmation should be emitted at or after this timestamp.
    pub cancel_confirm_at: Option<DateTime<Utc>>,
}

/// Paper trading executor for simulating order execution against live market data.
///
/// This executor:
/// - Maintains pending orders in memory
/// - Exposes `check_fills_from_trade()` for continuous fill detection from live trades
/// - Implements `OrderExecutor` trait for integration with TradeServer
/// - Optionally enforces inventory constraints on sell orders
/// - Optionally records Prometheus metrics for observability
/// - Optionally simulates order placement latency for realistic fill modeling
///
/// Unlike `BacktestOrderExecutor`, this executor is designed for continuous operation
/// where trade events arrive one at a time from a live feed.
#[derive(Clone)]
pub struct PaperTradingOrderExecutor {
    /// Pending limit orders awaiting fill (keyed by order_id)
    pending_orders: Arc<RwLock<HashMap<String, PendingPaperOrder>>>,
    /// Counter for generating unique order IDs
    order_id_counter: Arc<AtomicU64>,
    /// Fill simulation configuration
    config: PaperTradingConfig,
    /// Optional Prometheus metrics for observability
    metrics: Option<PaperTradingMetrics>,
    /// Canonical lifecycle authority for paper limit-order transitions.
    lifecycle_engine: Arc<StdMutex<LifecycleEngine>>,
}

impl PaperTradingOrderExecutor {
    /// Create a new paper trading order executor with default configuration.
    ///
    /// By default, inventory constraints are enforced (no naked shorts) and
    /// no latency simulation is applied.
    pub fn new() -> Self {
        Self::with_config(PaperTradingConfig::default())
    }

    /// Create a new paper trading order executor with custom configuration.
    ///
    /// # Arguments
    /// * `config` - Fill simulation configuration
    ///
    /// # Example
    /// ```rust,ignore
    /// // Default config
    /// PaperTradingOrderExecutor::new()
    ///
    /// // Custom fill simulation
    /// PaperTradingOrderExecutor::with_config(PaperTradingConfig {
    ///     enforce_inventory_constraints: false,
    ///     latency_config: Some(latency_config),
    /// })
    ///
    /// // Just latency, default inventory constraints
    /// PaperTradingOrderExecutor::with_config(PaperTradingConfig {
    ///     latency_config: Some(latency_config),
    ///     ..Default::default()
    /// })
    /// ```
    pub fn with_config(config: PaperTradingConfig) -> Self {
        Self {
            pending_orders: Arc::new(RwLock::new(HashMap::new())),
            order_id_counter: Arc::new(AtomicU64::new(1)),
            config,
            metrics: None,
            lifecycle_engine: Arc::new(StdMutex::new(LifecycleEngine::new())),
        }
    }

    /// Set Prometheus metrics for this executor.
    ///
    /// When metrics are set, the executor will record:
    /// - Order placements (labeled by side)
    /// - Order cancellations
    /// - Order fills (labeled by side, with volume and latency)
    /// - Pending order count (gauge)
    ///
    /// # Arguments
    /// * `metrics` - The metrics instance to use
    pub fn with_metrics(mut self, metrics: PaperTradingMetrics) -> Self {
        self.metrics = Some(metrics);
        self
    }

    /// Generate a unique order ID for this paper trading session.
    fn generate_order_id(&self) -> String {
        let id = self.order_id_counter.fetch_add(1, Ordering::SeqCst);
        format!("paper-order-{}", id)
    }

    /// Get all pending orders (for testing/inspection).
    pub async fn get_pending_orders(&self) -> Vec<PendingPaperOrder> {
        let orders = self.pending_orders.read().await;
        orders.values().cloned().collect()
    }

    /// Get a pending order by ID.
    pub async fn get_pending_order(&self, order_id: &str) -> Option<PendingPaperOrder> {
        let orders = self.pending_orders.read().await;
        orders.get(order_id).cloned()
    }

    /// Get the count of pending orders.
    pub async fn pending_order_count(&self) -> usize {
        let orders = self.pending_orders.read().await;
        orders.len()
    }

    /// Returns whether inventory constraints are enforced.
    pub fn enforces_inventory_constraints(&self) -> bool {
        self.config.enforce_inventory_constraints
    }

    /// Returns the fill simulation configuration.
    pub fn config(&self) -> &PaperTradingConfig {
        &self.config
    }

    /// Compute the eligible_for_fills_at timestamp for a new order.
    ///
    /// If latency simulation is enabled, adds a random latency within the configured range.
    /// Otherwise, returns the order timestamp (immediate eligibility).
    fn compute_eligibility_time(&self, order_timestamp: DateTime<Utc>) -> DateTime<Utc> {
        match &self.config.latency_config {
            Some(latency_config) => {
                let mut rng = rand::thread_rng();
                let order_latency = rng.gen_range(
                    latency_config.min_place_latency_ms..=latency_config.max_place_latency_ms,
                );
                order_timestamp + Duration::milliseconds(order_latency as i64)
            }
            None => order_timestamp, // No latency simulation - immediate eligibility
        }
    }

    fn sample_cancel_latency_ms(&self) -> Option<u64> {
        self.config.latency_config.as_ref().map(|latency_config| {
            let min_cancel = latency_config
                .min_cancel_latency_ms
                .unwrap_or(latency_config.min_place_latency_ms);
            let max_cancel = latency_config
                .max_cancel_latency_ms
                .unwrap_or(latency_config.max_place_latency_ms);
            let mut rng = rand::thread_rng();
            rng.gen_range(min_cancel..=max_cancel)
        })
    }

    fn compute_cancel_confirmation_time(&self, base_time: DateTime<Utc>) -> Option<DateTime<Utc>> {
        self.sample_cancel_latency_ms()
            .map(|latency_ms| base_time + Duration::milliseconds(latency_ms as i64))
    }

    fn lifecycle_order_ref(order_id: &str) -> LifecycleOrderRef {
        LifecycleOrderRef::ClientOrderId(order_id.to_string())
    }

    fn lifecycle_record_place_request(
        &self,
        order_id: &str,
        pending: &PendingPaperOrder,
    ) -> Result<()> {
        let mut lifecycle = self
            .lifecycle_engine
            .lock()
            .expect("paper lifecycle mutex poisoned");
        lifecycle
            .record_place_request(LifecyclePlaceRequest {
                lifecycle_id: Some(format!("paper-{order_id}")),
                client_order_id: order_id.to_string(),
                mint: pending.mint.clone(),
                market: pending.market.clone(),
                side: pending.side,
                price: pending.price,
                size: pending.original_size,
                time_in_force: pending.time_in_force,
                signal_id: pending.signal_id.clone(),
            })
            .map_err(|err| anyhow!("failed to record paper lifecycle place request: {err}"))?;
        Ok(())
    }

    fn lifecycle_record_place_success(&self, order_id: &str) -> Result<LifecycleState> {
        let mut lifecycle = self
            .lifecycle_engine
            .lock()
            .expect("paper lifecycle mutex poisoned");
        let order = lifecycle
            .record_place_success(LifecyclePlaceSuccess {
                order_ref: Self::lifecycle_order_ref(order_id),
                venue_order_id: order_id.to_string(),
            })
            .map_err(|err| anyhow!("failed to record paper lifecycle place success: {err}"))?;
        Ok(order.state)
    }

    fn lifecycle_record_cancel_request_state(
        &self,
        order_id: &str,
    ) -> Result<Option<LifecycleState>> {
        let mut lifecycle = self
            .lifecycle_engine
            .lock()
            .expect("paper lifecycle mutex poisoned");
        match lifecycle
            .record_cancel_request(LifecycleCancelRequest {
                order_ref: Self::lifecycle_order_ref(order_id),
            })
            .map_err(|err| anyhow!("failed to record paper lifecycle cancel request: {err}"))?
        {
            LifecycleCancelRequestOutcome::Updated(order) => Ok(Some(order.state)),
            LifecycleCancelRequestOutcome::IgnoredUnknownOrder => Ok(None),
        }
    }

    fn lifecycle_record_cancel_confirmed(&self, order_id: &str) -> Result<bool> {
        let mut lifecycle = self
            .lifecycle_engine
            .lock()
            .expect("paper lifecycle mutex poisoned");
        let order_ref = Self::lifecycle_order_ref(order_id);
        let previous_state = lifecycle.get(&order_ref).map(|order| order.state);
        let updated = lifecycle
            .record_cancel_confirmed(LifecycleCancelConfirmed {
                order_ref,
                venue_order_id: Some(order_id.to_string()),
            })
            .map_err(|err| {
                anyhow!("failed to record paper lifecycle cancel confirmation: {err}")
            })?;
        Ok(!matches!(
            previous_state,
            Some(LifecycleState::Terminal(TerminalReason::Cancelled))
        ) && matches!(
            updated.state,
            LifecycleState::Terminal(TerminalReason::Cancelled)
        ))
    }

    fn lifecycle_record_fill_evidence(
        &self,
        order_id: &str,
        filled_size: f64,
    ) -> Result<(LifecycleState, f64)> {
        let mut lifecycle = self
            .lifecycle_engine
            .lock()
            .expect("paper lifecycle mutex poisoned");
        let order = lifecycle
            .record_fill_evidence(LifecycleFillEvidence {
                order_ref: Self::lifecycle_order_ref(order_id),
                filled_size,
            })
            .map_err(|err| anyhow!("failed to record paper lifecycle fill evidence: {err}"))?;
        Ok((order.state, order.remaining_size))
    }

    fn lifecycle_state(&self, order_id: &str) -> Option<LifecycleState> {
        let lifecycle = self
            .lifecycle_engine
            .lock()
            .expect("paper lifecycle mutex poisoned");
        lifecycle
            .get(&Self::lifecycle_order_ref(order_id))
            .map(|order| order.state)
    }

    /// Helper to convert OrderSide to string for metrics.
    fn side_to_str(side: OrderSide) -> &'static str {
        match side {
            OrderSide::Buy => "buy",
            OrderSide::Sell => "sell",
        }
    }

    /// Process a Polymarket trade event and check for fills against pending orders.
    ///
    /// This is the primary method for paper trading fill detection. Call this method
    /// whenever a live trade event is received from the market data feed.
    ///
    /// Trade-based fill logic:
    /// - BID orders (we're buying) fill when SELL trades cross at or below our bid price
    /// - ASK orders (we're selling) fill when BUY trades cross at or above our ask price
    ///
    /// # Arguments
    /// * `trade` - The Polymarket trade event to process
    /// * `inventory` - Map of asset_id to current inventory. Used for inventory constraint checking
    ///   when `enforce_inventory_constraints` is enabled.
    /// * `available_quote` - Available quote balance. Buy fills that would exceed this are skipped.
    ///
    /// # Returns
    /// A vector of `LimitOrderEvent`s for any orders that were filled (partially or fully).
    pub async fn check_fills_from_trade(
        &self,
        trade: &PolymarketTradeEvent,
        inventory: &HashMap<String, f64>,
        available_quote: f64,
    ) -> Vec<LimitOrderEvent> {
        let mut lifecycle_events = Vec::new();
        let mut orders = self.pending_orders.write().await;

        // Track inventory changes within this call to handle multiple fills correctly
        let mut inventory_changes: HashMap<String, f64> = HashMap::new();
        // Track quote changes within this call to handle multiple buy fills correctly
        let mut quote_changes: f64 = 0.0;

        // Collect order IDs to remove (fully filled orders)
        let mut orders_to_remove = Vec::new();

        // Get trade timestamp for eligibility checks
        let trade_timestamp =
            DateTime::from_timestamp_millis(trade.timestamp).unwrap_or_else(Utc::now);

        let order_ids: Vec<String> = orders.keys().cloned().collect();

        // Check each pending order for potential fill
        for order_id in order_ids {
            let Some(pending) = orders.get_mut(&order_id) else {
                continue;
            };

            let mut lifecycle_state = match self.lifecycle_state(&order_id) {
                Some(state) => state,
                None => {
                    debug!(
                        order_id = %order_id,
                        "Skipping lifecycle processing - lifecycle record missing"
                    );
                    continue;
                }
            };

            // In latency mode, placement confirmation is deferred until lifecycle evidence arrives.
            if matches!(lifecycle_state, LifecycleState::SubmitPending)
                && trade_timestamp >= pending.eligible_for_fills_at
            {
                match self.lifecycle_record_place_success(&order_id) {
                    Ok(updated_state) => {
                        lifecycle_state = updated_state;
                        if matches!(lifecycle_state, LifecycleState::Open) {
                            lifecycle_events.push(LimitOrderEvent::OrderPlaced {
                                order_id: order_id.clone(),
                                mint: pending.mint.clone(),
                                market: pending.market.clone(),
                                price: pending.price,
                                size: pending.original_size,
                                side: pending.side,
                                timestamp: trade_timestamp,
                                signal_id: pending.signal_id.clone(),
                                context: pending.context.clone(),
                            });
                            if let Some(ref metrics) = self.metrics {
                                metrics.record_order_placed(Self::side_to_str(pending.side));
                            }
                        } else if matches!(lifecycle_state, LifecycleState::CancelPending) {
                            let base_time = trade_timestamp.max(pending.eligible_for_fills_at);
                            let candidate = self
                                .compute_cancel_confirmation_time(base_time)
                                .unwrap_or(base_time);
                            let scheduled = pending
                                .cancel_confirm_at
                                .map_or(candidate, |existing| existing.min(candidate));
                            pending.cancel_confirm_at = Some(scheduled);
                        }
                    }
                    Err(err) => {
                        debug!(
                            order_id = %order_id,
                            err = ?err,
                            "Failed to transition submit-pending paper order to placed"
                        );
                        continue;
                    }
                }
            }

            if matches!(lifecycle_state, LifecycleState::CancelPending) {
                if pending.cancel_confirm_at.is_none() {
                    let base_time = trade_timestamp.max(pending.eligible_for_fills_at);
                    pending.cancel_confirm_at = self
                        .compute_cancel_confirmation_time(base_time)
                        .or(Some(base_time));
                }

                if let Some(cancel_confirm_at) = pending.cancel_confirm_at {
                    if trade_timestamp >= cancel_confirm_at {
                        match self.lifecycle_record_cancel_confirmed(&order_id) {
                            Ok(emitted) => {
                                if emitted {
                                    lifecycle_events.push(LimitOrderEvent::OrderCancelled {
                                        order_id: order_id.clone(),
                                        reason: Some("User cancelled".to_string()),
                                        timestamp: cancel_confirm_at,
                                    });
                                    if let Some(ref metrics) = self.metrics {
                                        metrics.record_order_cancelled();
                                    }
                                }
                            }
                            Err(err) => {
                                debug!(
                                    order_id = %order_id,
                                    err = ?err,
                                    "Failed to record lifecycle cancel confirmation"
                                );
                            }
                        }
                        orders_to_remove.push(order_id.clone());
                        continue;
                    }
                }
            }

            if !matches!(
                lifecycle_state,
                LifecycleState::Open | LifecycleState::CancelPending
            ) {
                continue;
            }

            // Only process orders for the same asset
            if pending.mint != trade.asset_id {
                continue;
            }

            // Skip orders that weren't on the book yet when this trade happened (latency simulation)
            if trade_timestamp < pending.eligible_for_fills_at {
                debug!(
                    order_id = %order_id,
                    trade_ts = %trade_timestamp,
                    eligible_at = %pending.eligible_for_fills_at,
                    "Skipping fill check - order not yet eligible"
                );
                continue;
            }

            // Trade-based fill logic:
            // - Our BID order (buying) fills when someone SELLs at or below our bid price
            // - Our ASK order (selling) fills when someone BUYs at or above our ask price
            let should_fill = match (&pending.side, &trade.side) {
                // We're bidding (buying), trade is a sell hitting bids
                (OrderSide::Buy, TradeSide::Sell) => trade.price <= pending.price,
                // We're asking (selling), trade is a buy lifting asks
                (OrderSide::Sell, TradeSide::Buy) => trade.price >= pending.price,
                // Other combinations don't result in a fill
                _ => false,
            };

            if should_fill {
                // For sell orders, check inventory constraint if enabled
                let available_inventory = if self.config.enforce_inventory_constraints
                    && pending.side == OrderSide::Sell
                {
                    let base_inventory = inventory.get(&pending.mint).copied().unwrap_or(0.0);
                    let changes = inventory_changes.get(&pending.mint).copied().unwrap_or(0.0);
                    let available = base_inventory + changes;

                    if available <= 0.0 {
                        // No inventory to sell - skip this fill
                        debug!(
                            order_id = %order_id,
                            mint = %pending.mint,
                            available_inventory = available,
                            "Skipping sell fill - no inventory available"
                        );
                        continue;
                    }
                    Some(available)
                } else {
                    None
                };

                // Calculate fill size (capped by order remaining, trade size, and available inventory)
                let mut fill_size = pending.remaining_size.min(trade.size);

                // Cap by available inventory for sell orders if constraint is enabled
                if let Some(available) = available_inventory {
                    fill_size = fill_size.min(available);
                }

                // For buy orders, check quote balance constraint.
                // This is Layer 2 of the quote balance defense - it catches race conditions
                // where multiple markets independently generated buy signals.
                if pending.side == OrderSide::Buy {
                    let quote_required = fill_size * pending.price;
                    let effective_available = available_quote + quote_changes;

                    if effective_available < quote_required {
                        // Check if we can do a partial fill
                        let max_fill_by_quote = effective_available / pending.price;
                        if max_fill_by_quote <= 0.0 {
                            debug!(
                                order_id = %order_id,
                                mint = %pending.mint,
                                quote_required = quote_required,
                                available_quote = effective_available,
                                "Skipping buy fill - insufficient quote balance"
                            );
                            continue;
                        }
                        // Reduce fill size to what we can afford
                        fill_size = fill_size.min(max_fill_by_quote);
                        debug!(
                            order_id = %order_id,
                            mint = %pending.mint,
                            original_fill_size = pending.remaining_size.min(trade.size),
                            reduced_fill_size = fill_size,
                            available_quote = effective_available,
                            "Reducing buy fill size due to quote balance constraint"
                        );
                    }
                }

                // Skip if fill size is effectively zero
                if fill_size <= 0.0 {
                    continue;
                }

                let (updated_state, remaining_size) =
                    match self.lifecycle_record_fill_evidence(&order_id, fill_size) {
                        Ok(state_and_remaining) => state_and_remaining,
                        Err(err) => {
                            debug!(
                                order_id = %order_id,
                                err = ?err,
                                "Failed to record paper fill evidence"
                            );
                            continue;
                        }
                    };
                pending.remaining_size = remaining_size;

                if matches!(
                    updated_state,
                    LifecycleState::Terminal(TerminalReason::Cancelled)
                        | LifecycleState::Terminal(TerminalReason::Rejected)
                        | LifecycleState::Terminal(TerminalReason::Expired)
                ) {
                    orders_to_remove.push(order_id.clone());
                    continue;
                }

                // Track inventory and quote changes
                if pending.side == OrderSide::Sell {
                    *inventory_changes.entry(pending.mint.clone()).or_insert(0.0) -= fill_size;
                    // Selling increases quote balance
                    quote_changes += fill_size * pending.price;
                } else {
                    // Buy orders increase inventory and decrease quote balance
                    *inventory_changes.entry(pending.mint.clone()).or_insert(0.0) += fill_size;
                    quote_changes -= fill_size * pending.price;
                }

                // Calculate fill latency in milliseconds
                let fill_latency_ms = (trade_timestamp - pending.placed_at)
                    .num_milliseconds()
                    .max(0) as f64;

                // Record fill metrics
                if let Some(ref metrics) = self.metrics {
                    let side_str = Self::side_to_str(pending.side);
                    metrics.record_fill(side_str, fill_size, fill_latency_ms);
                }

                if pending.remaining_size <= 0.0 {
                    // Fully filled - emit OrderPartiallyFilled with remaining=0
                    debug!(
                        order_id = %order_id,
                        fill_price = pending.price,
                        fill_size = fill_size,
                        fill_latency_ms = fill_latency_ms,
                        "Paper order fully filled"
                    );
                    lifecycle_events.push(LimitOrderEvent::OrderPartiallyFilled {
                        order_id: order_id.clone(),
                        mint: pending.mint.clone(),
                        side: pending.side,
                        filled_size: fill_size,
                        remaining_size: 0.0,
                        fill_price: pending.price, // Fill at our order price, not trade price
                        timestamp: trade_timestamp,
                        signal_id: pending.signal_id.clone(),
                        exit_mode: pending.exit_mode,
                    });
                    orders_to_remove.push(order_id.clone());
                } else {
                    // Partially filled
                    debug!(
                        order_id = %order_id,
                        fill_price = pending.price,
                        fill_size = fill_size,
                        remaining_size = pending.remaining_size,
                        fill_latency_ms = fill_latency_ms,
                        "Paper order partially filled"
                    );
                    lifecycle_events.push(LimitOrderEvent::OrderPartiallyFilled {
                        order_id: order_id.clone(),
                        mint: pending.mint.clone(),
                        side: pending.side,
                        filled_size: fill_size,
                        remaining_size: pending.remaining_size,
                        fill_price: pending.price, // Fill at our order price, not trade price
                        timestamp: trade_timestamp,
                        signal_id: pending.signal_id.clone(),
                        exit_mode: pending.exit_mode,
                    });
                }
            }
        }

        // Remove fully filled orders
        for order_id in orders_to_remove {
            orders.remove(&order_id);
        }

        // Update pending orders gauge
        if let Some(ref metrics) = self.metrics {
            metrics.set_pending_orders(orders.len());
        }

        lifecycle_events
    }
}

impl Default for PaperTradingOrderExecutor {
    fn default() -> Self {
        Self::new()
    }
}

#[async_trait]
impl OrderExecutor for PaperTradingOrderExecutor {
    /// Execute a market order - returns rejected since paper trading only supports limit orders.
    ///
    /// Paper trading mode is designed for orderbook/CLOB venues where market orders
    /// would immediately execute. For simplicity, we only support limit orders.
    #[instrument(skip(self))]
    async fn execute_market_order(&self, order: Order) -> Result<ExecutionEvent> {
        // Paper trading is designed for limit orders only
        // Market orders would need immediate fill simulation which complicates the model
        Ok(ExecutionEvent::OrderRejected {
            mint: order.mint,
            reason: "Paper trading mode only supports limit orders".to_string(),
        })
    }

    /// Handle token trade events - no-op for paper trading.
    ///
    /// Trade events are processed via `check_fills_from_trade()` which is called
    /// explicitly by the TradeServer when in paper trading mode.
    #[instrument(skip(self))]
    async fn handle_token_trade(&self, _trade: &TokenTradeEvent) -> Result<()> {
        // No-op - paper trading processes trades via check_fills_from_trade()
        Ok(())
    }

    /// Execute a limit order by adding it to the pending orders map.
    ///
    /// For ImmediateOrCancel (IOC) orders, this implementation does not attempt
    /// immediate fill checking - it simply places the order and relies on
    /// subsequent trade events to trigger fills.
    #[instrument(skip(self))]
    async fn execute_limit_order(&self, order: Order) -> Result<LimitOrderEvent> {
        let (size, limit_price, side, time_in_force) = match &order.order_type {
            OrderType::LimitBuy {
                quote_amount,
                limit_price,
                time_in_force,
            } => {
                // Convert quote_amount to base units (token amount) for consistent tracking.
                // Intent signals express size in base units, so reconciliation comparisons
                // need the same unit to avoid spurious cancel/replace cycles.
                let base_size = *quote_amount / *limit_price;
                (base_size, *limit_price, OrderSide::Buy, *time_in_force)
            }
            OrderType::LimitSell {
                token_amount,
                limit_price,
                time_in_force,
                ..
            } => (*token_amount, *limit_price, OrderSide::Sell, *time_in_force),
            _ => {
                return Err(anyhow!(
                    "execute_limit_order called with non-limit order type: {:?}",
                    order.order_type
                ));
            }
        };

        let order_id = self.generate_order_id();

        // Compute when this order becomes eligible for fills (latency simulation)
        let eligible_for_fills_at = self.compute_eligibility_time(order.timestamp);
        let deferred_lifecycle = self.config.latency_config.is_some();

        // Create pending order
        let pending = PendingPaperOrder {
            order_id: order_id.clone(),
            mint: order.mint.clone(),
            market: order.market.clone(),
            side,
            price: limit_price,
            original_size: size,
            remaining_size: size,
            placed_at: order.timestamp,
            time_in_force,
            signal_id: order.signal_id.clone(),
            exit_mode: order.exit_mode,
            context: order.context.clone(),
            eligible_for_fills_at,
            cancel_confirm_at: None,
        };

        self.lifecycle_record_place_request(&order_id, &pending)?;
        if !deferred_lifecycle {
            let lifecycle_state = self.lifecycle_record_place_success(&order_id)?;
            if !matches!(lifecycle_state, LifecycleState::Open) {
                return Err(anyhow!(
                    "unexpected lifecycle state after immediate place success for {}: {:?}",
                    order_id,
                    lifecycle_state
                ));
            }
        }

        // Add to pending orders and update metrics
        {
            let mut orders = self.pending_orders.write().await;
            orders.insert(order_id.clone(), pending);

            // Record metrics
            if let Some(ref metrics) = self.metrics {
                if !deferred_lifecycle {
                    metrics.record_order_placed(Self::side_to_str(side));
                }
                metrics.set_pending_orders(orders.len());
            }
        }

        debug!(
            order_id = %order_id,
            mint = %order.mint,
            side = ?side,
            price = limit_price,
            size = size,
            "Paper limit order placed"
        );

        Ok(LimitOrderEvent::OrderPlaced {
            order_id,
            mint: order.mint,
            market: order.market,
            price: limit_price,
            size,
            side,
            timestamp: order.timestamp,
            signal_id: order.signal_id,
            context: order.context,
        })
    }

    /// Cancel a pending limit order by its order ID.
    #[instrument(skip(self))]
    async fn cancel_order(&self, order_id: &str) -> Result<LimitOrderEvent> {
        let now = Utc::now();
        let deferred_lifecycle = self.config.latency_config.is_some();
        let lifecycle_state = self.lifecycle_record_cancel_request_state(order_id)?;

        let Some(lifecycle_state) = lifecycle_state else {
            debug!(
                order_id = %order_id,
                "Order not found during cancel (likely already filled or cancelled)"
            );
            return Ok(LimitOrderEvent::OrderCancelled {
                order_id: order_id.to_string(),
                reason: Some("Order already removed (filled or cancelled)".to_string()),
                timestamp: now,
            });
        };

        if matches!(lifecycle_state, LifecycleState::Terminal(_)) {
            debug!(
                order_id = %order_id,
                state = ?lifecycle_state,
                "Order already terminal during cancel request"
            );
            return Ok(LimitOrderEvent::OrderCancelled {
                order_id: order_id.to_string(),
                reason: Some("Order already removed (filled or cancelled)".to_string()),
                timestamp: now,
            });
        }

        let mut orders = self.pending_orders.write().await;
        let cancel_confirm_at = {
            let Some(pending) = orders.get_mut(order_id) else {
                debug!(
                    order_id = %order_id,
                    "Order missing from pending set during cancel request"
                );
                return Ok(LimitOrderEvent::OrderCancelled {
                    order_id: order_id.to_string(),
                    reason: Some("Order already removed (filled or cancelled)".to_string()),
                    timestamp: now,
                });
            };

            if deferred_lifecycle {
                let base_time = pending.eligible_for_fills_at.max(now);
                let candidate = self
                    .compute_cancel_confirmation_time(base_time)
                    .unwrap_or(base_time);
                let scheduled = pending
                    .cancel_confirm_at
                    .map_or(candidate, |existing| existing.min(candidate));
                pending.cancel_confirm_at = Some(scheduled);
                scheduled
            } else {
                now
            }
        };

        if deferred_lifecycle {
            debug!(
                order_id = %order_id,
                cancel_confirm_at = %cancel_confirm_at,
                "Paper cancel request accepted; awaiting lifecycle confirmation"
            );
            return Ok(LimitOrderEvent::OrderCancelled {
                order_id: order_id.to_string(),
                reason: Some("User cancelled".to_string()),
                timestamp: cancel_confirm_at,
            });
        }

        if let Some(pending) = orders.remove(order_id) {
            let _ = self.lifecycle_record_cancel_confirmed(order_id)?;
            if let Some(ref metrics) = self.metrics {
                metrics.record_order_cancelled();
                metrics.set_pending_orders(orders.len());
            }

            debug!(
                order_id = %order_id,
                remaining_size = pending.remaining_size,
                "Paper limit order cancelled"
            );
            Ok(LimitOrderEvent::OrderCancelled {
                order_id: order_id.to_string(),
                reason: Some("User cancelled".to_string()),
                timestamp: cancel_confirm_at,
            })
        } else {
            debug!(
                order_id = %order_id,
                "Order not found during cancel (likely already filled or cancelled)"
            );
            Ok(LimitOrderEvent::OrderCancelled {
                order_id: order_id.to_string(),
                reason: Some("Order already removed (filled or cancelled)".to_string()),
                timestamp: now,
            })
        }
    }

    /// Returns true - the paper trading executor supports limit orders.
    fn supports_limit_orders(&self) -> bool {
        true
    }

    /// Execute a pair redemption operation in paper trading mode.
    ///
    /// For binary markets, this simulates redeeming paired Up + Down tokens for
    /// the underlying quote currency. Each pair redeems for exactly $1.00.
    ///
    /// The paper executor simply returns a successful redemption event.
    /// The PositionManager handles the actual position and balance updates
    /// when it processes the RedemptionEvent.
    #[instrument(skip(self))]
    async fn execute_redemption(&self, action: &RedemptionAction) -> Result<RedemptionEvent> {
        debug!(
            market = %action.market,
            up_asset = %action.up_asset_id,
            down_asset = %action.down_asset_id,
            quantity = action.quantity,
            "Executing paper redemption"
        );

        // In binary markets, 1 Up + 1 Down = $1.00
        let quote_received = action.quantity;

        Ok(RedemptionEvent::RedemptionCompleted {
            market: action.market.clone(),
            up_asset_id: action.up_asset_id.clone(),
            down_asset_id: action.down_asset_id.clone(),
            quantity: action.quantity,
            quote_received,
            timestamp: action.timestamp,
        })
    }

    /// Returns true - the paper trading executor supports pair redemption.
    fn supports_redemption(&self) -> bool {
        true
    }

    /// Check for simulated fills from a Polymarket trade event.
    ///
    /// This implements the `OrderExecutor` trait method by delegating to the
    /// existing `check_fills_from_trade` method. The paper trading executor
    /// simulates order fills based on market trade events crossing pending
    /// limit order prices.
    async fn check_fills_from_trade(
        &self,
        trade: &PolymarketTradeEvent,
        inventory: &HashMap<String, f64>,
        available_quote: f64,
    ) -> Vec<LimitOrderEvent> {
        // Delegate to the existing method on self
        PaperTradingOrderExecutor::check_fills_from_trade(self, trade, inventory, available_quote)
            .await
    }

    /// Returns true - the paper trading executor simulates fills from trade events.
    fn simulates_fills(&self) -> bool {
        true
    }

    fn defers_limit_order_events(&self) -> bool {
        self.config.latency_config.is_some()
    }
}
