use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use solana_sdk::signature::Signature;

use crate::position::ExitMode;

/// Time-in-force options for limit orders.
///
/// Specifies how long an order remains active before being cancelled.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum TimeInForce {
    /// Order remains active until explicitly cancelled or filled
    GoodTilCancelled,
    /// Fill what's possible immediately, cancel the rest
    ImmediateOrCancel,
    /// Fill the entire order immediately or cancel entirely
    FillOrKill,
}

impl Default for TimeInForce {
    fn default() -> Self {
        TimeInForce::GoodTilCancelled
    }
}

/// Mode for transaction simulation before execution.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum SimulationMode {
    Pure,     // Current simulation that just returns fake values
    RpcBased, // New simulation that uses RPC endpoint simulation
    Disabled, // No simulation (real execution)
}

/// Side of an order (buy or sell).
///
/// Used for limit orders where the side is explicit rather than determined
/// by the order type variant.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum OrderSide {
    Buy,
    Sell,
}

/// Events that track the lifecycle of a limit order.
///
/// These events are emitted by orderbook venues (like Polymarket) to track
/// order placement, fills, cancellations, and expirations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum LimitOrderEvent {
    /// Order was successfully placed on the venue's orderbook
    OrderPlaced {
        /// Unique order ID assigned by the venue
        order_id: String,
        /// Asset identifier (token mint or asset_id)
        mint: String,
        /// Market/condition ID (for orderbook venues)
        market: Option<String>,
        /// Price the order was placed at
        price: f64,
        /// Size of the order
        size: f64,
        /// Order side (buy or sell)
        side: OrderSide,
        /// When the order was placed
        timestamp: DateTime<Utc>,
        /// ID of the signal that originated this order
        signal_id: Option<String>,
        /// Arbitrary debug context data from the signal (e.g., fair price, inventory, orderbook state)
        context: Option<serde_json::Value>,
    },

    /// Order was partially filled (or fully filled with remaining_size = 0)
    OrderPartiallyFilled {
        /// Venue order ID
        order_id: String,
        /// Asset identifier (token mint or asset_id)
        mint: String,
        /// Order side (buy or sell)
        side: OrderSide,
        /// Amount filled in this execution
        filled_size: f64,
        /// Remaining unfilled amount
        remaining_size: f64,
        /// Price at which this fill occurred
        fill_price: f64,
        /// When the partial fill occurred
        timestamp: DateTime<Utc>,
        /// ID of the signal that originated this order
        signal_id: Option<String>,
        /// Exit mode for positions created from this fill.
        /// Propagated from the order so it's available even after the order is removed.
        exit_mode: Option<ExitMode>,
    },

    /// Order was cancelled (by user or system)
    OrderCancelled {
        /// Venue order ID
        order_id: String,
        /// Reason for cancellation (if provided)
        reason: Option<String>,
        /// When the cancellation occurred
        timestamp: DateTime<Utc>,
    },

    /// Order expired due to time-in-force constraints
    OrderExpired {
        /// Venue order ID
        order_id: String,
        /// When the expiration occurred
        timestamp: DateTime<Utc>,
    },

    /// Order was rejected by the venue
    OrderRejected {
        /// Reason for rejection
        reason: String,
    },
}

impl LimitOrderEvent {
    /// Returns the order ID if this event has one
    pub fn order_id(&self) -> Option<&str> {
        match self {
            LimitOrderEvent::OrderPlaced { order_id, .. }
            | LimitOrderEvent::OrderPartiallyFilled { order_id, .. }
            | LimitOrderEvent::OrderCancelled { order_id, .. }
            | LimitOrderEvent::OrderExpired { order_id, .. } => Some(order_id),
            LimitOrderEvent::OrderRejected { .. } => None,
        }
    }

    /// Returns true if this event indicates the order is no longer active
    pub fn is_terminal(&self) -> bool {
        matches!(
            self,
            LimitOrderEvent::OrderCancelled { .. }
                | LimitOrderEvent::OrderExpired { .. }
                | LimitOrderEvent::OrderRejected { .. }
        )
    }
}

/// Events generated by the execution layer for market orders.
///
/// These events are generated after market order execution (AMM swaps, DEX trades)
/// and are used to update position state.
#[derive(Debug, Clone, PartialEq)]
pub enum ExecutionEvent {
    OrderFilled {
        mint: String,
        /// Token amount change in standard unit, not base unit.
        /// Positive for buys, negative for sells.
        token_amount_change: f64,
        quote_amount_change: Option<f64>,
        price: Option<f64>,
        timestamp: DateTime<Utc>,
        slippage: Option<f64>,
        clear_position: bool,
        force_position_clear: bool,
        execution_latency_in_slots: Option<u64>,
        /// Slot when the transaction was confirmed (None if not confirmed)
        confirmed_slot: Option<u64>,
        /// Signature of the confirmed transaction (None if not confirmed)
        confirmed_signature: Option<Signature>,
        /// ID of the signal that triggered the original order
        signal_id: Option<String>,
        /// Exit mode for positions created from this fill.
        /// None means use the default (Automatic). Used to propagate StrategyManaged mode
        /// from intent-based signals through to position creation.
        exit_mode: Option<ExitMode>,
    },
    OrderRejected {
        mint: String,
        reason: String,
    },
}

/// Event emitted when a pair redemption operation completes.
///
/// In binary prediction markets, holding 1 Up + 1 Down token can be redeemed
/// for exactly $1 (quote currency). This event tracks the outcome of redemption
/// operations.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum RedemptionEvent {
    /// Redemption completed successfully
    RedemptionCompleted {
        /// Market/condition identifier
        market: String,
        /// Asset ID for the "Up" token
        up_asset_id: String,
        /// Asset ID for the "Down" token
        down_asset_id: String,
        /// Quantity of pairs redeemed
        quantity: f64,
        /// Quote currency received from redemption
        quote_received: f64,
        /// When the redemption occurred
        timestamp: DateTime<Utc>,
    },
    /// Redemption failed
    RedemptionFailed {
        /// Market/condition identifier
        market: String,
        /// Reason for failure
        reason: String,
        /// When the failure occurred
        timestamp: DateTime<Utc>,
    },
}

impl RedemptionEvent {
    /// Returns the market identifier for this event.
    pub fn market(&self) -> &str {
        match self {
            RedemptionEvent::RedemptionCompleted { market, .. } => market,
            RedemptionEvent::RedemptionFailed { market, .. } => market,
        }
    }

    /// Returns the timestamp of this event.
    pub fn timestamp(&self) -> DateTime<Utc> {
        match self {
            RedemptionEvent::RedemptionCompleted { timestamp, .. } => *timestamp,
            RedemptionEvent::RedemptionFailed { timestamp, .. } => *timestamp,
        }
    }

    /// Returns true if the redemption was successful.
    pub fn is_successful(&self) -> bool {
        matches!(self, RedemptionEvent::RedemptionCompleted { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_time_in_force_default() {
        assert_eq!(TimeInForce::default(), TimeInForce::GoodTilCancelled);
    }

    #[test]
    fn test_time_in_force_serialization() {
        let gtc = TimeInForce::GoodTilCancelled;
        let json = serde_json::to_string(&gtc).unwrap();
        assert_eq!(json, "\"GoodTilCancelled\"");

        let deserialized: TimeInForce = serde_json::from_str(&json).unwrap();
        assert_eq!(deserialized, TimeInForce::GoodTilCancelled);
    }

    #[test]
    fn test_order_side_serialization() {
        let buy = OrderSide::Buy;
        let sell = OrderSide::Sell;

        assert_eq!(serde_json::to_string(&buy).unwrap(), "\"Buy\"");
        assert_eq!(serde_json::to_string(&sell).unwrap(), "\"Sell\"");
    }

    #[test]
    fn test_limit_order_event_order_id() {
        let placed = LimitOrderEvent::OrderPlaced {
            order_id: "order123".to_string(),
            mint: "token".to_string(),
            market: None,
            price: 0.5,
            size: 100.0,
            side: OrderSide::Buy,
            timestamp: Utc::now(),
            signal_id: None,
            context: None,
        };
        assert_eq!(placed.order_id(), Some("order123"));

        let rejected = LimitOrderEvent::OrderRejected {
            reason: "insufficient funds".to_string(),
        };
        assert_eq!(rejected.order_id(), None);
    }

    #[test]
    fn test_limit_order_event_is_terminal() {
        let placed = LimitOrderEvent::OrderPlaced {
            order_id: "order123".to_string(),
            mint: "token".to_string(),
            market: None,
            price: 0.5,
            size: 100.0,
            side: OrderSide::Buy,
            timestamp: Utc::now(),
            signal_id: None,
            context: None,
        };
        assert!(!placed.is_terminal());

        let cancelled = LimitOrderEvent::OrderCancelled {
            order_id: "order123".to_string(),
            reason: Some("user requested".to_string()),
            timestamp: Utc::now(),
        };
        assert!(cancelled.is_terminal());

        let expired = LimitOrderEvent::OrderExpired {
            order_id: "order123".to_string(),
            timestamp: Utc::now(),
        };
        assert!(expired.is_terminal());

        let rejected = LimitOrderEvent::OrderRejected {
            reason: "price too high".to_string(),
        };
        assert!(rejected.is_terminal());

        let partial = LimitOrderEvent::OrderPartiallyFilled {
            order_id: "order123".to_string(),
            mint: "token".to_string(),
            side: OrderSide::Buy,
            filled_size: 50.0,
            remaining_size: 50.0,
            fill_price: 0.5,
            timestamp: Utc::now(),
            signal_id: None,
            exit_mode: None,
        };
        assert!(!partial.is_terminal());
    }

    #[test]
    fn test_limit_order_event_serialization() {
        let event = LimitOrderEvent::OrderPlaced {
            order_id: "order123".to_string(),
            mint: "token456".to_string(),
            market: Some("market789".to_string()),
            price: 0.65,
            size: 100.0,
            side: OrderSide::Buy,
            timestamp: DateTime::from_timestamp(1700000000, 0).unwrap(),
            signal_id: Some("signal-abc".to_string()),
            context: Some(serde_json::json!({"fair_price": 0.64})),
        };

        let json = serde_json::to_string(&event).unwrap();
        let deserialized: LimitOrderEvent = serde_json::from_str(&json).unwrap();

        assert_eq!(event, deserialized);
        assert!(json.contains("\"order_id\":\"order123\""));
        assert!(json.contains("\"mint\":\"token456\""));
    }

    #[test]
    fn test_redemption_event_completed() {
        let timestamp = DateTime::from_timestamp(1700000000, 0).unwrap();
        let event = RedemptionEvent::RedemptionCompleted {
            market: "MARKET-1".to_string(),
            up_asset_id: "UP".to_string(),
            down_asset_id: "DOWN".to_string(),
            quantity: 50.0,
            quote_received: 50.0,
            timestamp,
        };

        assert_eq!(event.market(), "MARKET-1");
        assert_eq!(event.timestamp(), timestamp);
        assert!(event.is_successful());
    }

    #[test]
    fn test_redemption_event_failed() {
        let timestamp = DateTime::from_timestamp(1700000000, 0).unwrap();
        let event = RedemptionEvent::RedemptionFailed {
            market: "MARKET-1".to_string(),
            reason: "insufficient balance".to_string(),
            timestamp,
        };

        assert_eq!(event.market(), "MARKET-1");
        assert_eq!(event.timestamp(), timestamp);
        assert!(!event.is_successful());
    }

    #[test]
    fn test_redemption_event_serialization() {
        let timestamp = DateTime::from_timestamp(1700000000, 0).unwrap();
        let event = RedemptionEvent::RedemptionCompleted {
            market: "MARKET-1".to_string(),
            up_asset_id: "UP-ASSET".to_string(),
            down_asset_id: "DOWN-ASSET".to_string(),
            quantity: 50.0,
            quote_received: 50.0,
            timestamp,
        };

        let json = serde_json::to_string(&event).unwrap();
        let deserialized: RedemptionEvent = serde_json::from_str(&json).unwrap();

        assert_eq!(event, deserialized);
        assert!(json.contains("\"market\":\"MARKET-1\""));
        assert!(json.contains("\"quantity\":50.0"));
    }
}
