use chrono::{DateTime, Utc};

use crate::execution::events::{OrderSide, TimeInForce};
use crate::position::ExitMode;

/// Internal representation of a pending limit order in the backtest executor.
///
/// This struct tracks the state of a limit order that has been placed but not yet
/// filled or cancelled.
#[derive(Debug, Clone)]
pub struct PendingBacktestOrder {
    /// Unique order identifier (generated by executor)
    pub order_id: String,
    /// Asset identifier (token mint or asset_id)
    pub mint: String,
    /// Market/condition ID (for orderbook venues)
    pub market: Option<String>,
    /// Order side (Buy or Sell)
    pub side: OrderSide,
    /// Limit price
    pub price: f64,
    /// Original order size
    pub original_size: f64,
    /// Remaining unfilled size
    pub remaining_size: f64,
    /// When the order was placed
    pub placed_at: DateTime<Utc>,
    /// Time-in-force constraint
    pub time_in_force: TimeInForce,
    /// Signal ID that originated this order
    pub signal_id: Option<String>,
    /// Exit mode for positions created from fills of this order.
    /// Used to propagate StrategyManaged mode from intent-based signals.
    pub exit_mode: Option<ExitMode>,
    /// Arbitrary debug context data from the signal
    pub context: Option<serde_json::Value>,
    /// Earliest timestamp when this order is eligible for fills.
    /// Models order placement latency.
    /// Orders are not matched against trades with timestamp < eligible_for_fills_at.
    pub eligible_for_fills_at: DateTime<Utc>,
    /// Timestamp when the order is no longer eligible for fills (cancel latency).
    /// If set, fills are only allowed for trades with timestamp < active_until.
    pub active_until: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub(super) struct QuoteLaneKey {
    pub(super) market: Option<String>,
    pub(super) mint: String,
    pub(super) side: OrderSide,
}

#[derive(Debug, Clone)]
pub(super) struct QuoteRequest {
    pub(super) mint: String,
    pub(super) market: Option<String>,
    pub(super) side: OrderSide,
    pub(super) price: f64,
    pub(super) size: f64,
    pub(super) time_in_force: TimeInForce,
    pub(super) signal_id: Option<String>,
    pub(super) exit_mode: Option<ExitMode>,
    pub(super) context: Option<serde_json::Value>,
}

#[derive(Debug, Clone)]
pub(super) struct ScheduledQuote {
    pub(super) order_id: String,
    pub(super) quote: QuoteRequest,
}

#[derive(Debug, Clone)]
pub(super) enum QuoteLaneState {
    Idle,
    Placing {
        scheduled: ScheduledQuote,
        live_at: DateTime<Utc>,
        cancel_at: Option<DateTime<Utc>>,
    },
    Live {
        order_id: String,
    },
    Canceling {
        order_id: String,
        remove_at: DateTime<Utc>,
        pending_replacement: Option<ScheduledQuote>,
    },
}
